version: '2'
catalog:
  name: "rails-mysql"
  version: "v0.0.2"
  description: 'simple app'
  questions:
    - variable: rails_env
      description: 'example "production"  "development"'
      label: "rails app environment"
      required: true
      type: 'string'
      default: 'development'
    - variable: repo_name
      description: 'example "okamuroshogo/rails-sample"'
      label: "rails app github repository name"
      required: true
      type: 'string'
      default: ''
    - variable: repo_branch
      description: 'example "master"'
      label: "rails app github repository branch"
      required: true
      type: 'string'
      default: 'master'
    - variable: repo_user
      description: 'repo user'
      label: 'repo user'
      required: true
      type: 'string'
    - variable: repo_pass
      description: 'repo pass'
      label: 'repo pass'
      required: true
      type: 'password'
    - variable: mysql_user
      description: '{rails_root}/config/database.yml'
      label: 'MySQL user name'
      required: true
      type: 'string'
      default: 'user'
    - variable: mysql_pass
      description: '{rails_root}/config/database.yml'
      label: 'MySQL pass'
      required: true
      type: 'password'
      default: 'password'
    - variable: mysql_db
      description: '{rails_root}/config/database.yml'
      label: 'MySQL db name'
      required: true
      type: 'string'
      default: 'production_db' 
services:
  rails:
    scale: 1
  mysql:
    scale: 1
